import type { Match, Options, Request, Reason } from './types';
export const demoOptions: Options = { cities: ['Алматы', 'Астана', 'Зарубежье'], categories: ['Ведущий', 'Флорист'], event_formats: ['корпоратив', 'свадьба'], languages: ['русский', 'казахский'], date_min: '2026-09-23', date_max: '2026-12-31', dataset_count: 66 };
export const examples: { title: string; request: Request }[] = [
 { title: 'Ведущие осенью', request: { city: 'Алматы', date: '2026-10-10', event_format: 'корпоратив', category: 'Ведущий', budget_kzt: 1000000, language: 'русский', duration_hours: 4 } },
 { title: 'Редкие флористы', request: { city: 'Алматы', date: '2026-10-10', event_format: 'свадьба', category: 'Флорист', budget_kzt: 300000, language: null, duration_hours: null } },
 { title: 'Бюджет 1 000 ₸', request: { city: 'Алматы', date: '2026-10-10', event_format: 'корпоратив', category: 'Ведущий', budget_kzt: 1000, language: null, duration_hours: null } },
 { title: 'Нет категории', request: { city: 'Зарубежье', date: '2026-10-10', event_format: 'свадьба', category: 'Флорист', budget_kzt: 300000, language: null, duration_hours: null } }
];
// Fixed UI scenarios, not a copy of the catalogue or a matching implementation.
export function demoMatch(request: Request): Match {
 const scenario = examples.findIndex(({ request: sample }) => Object.entries(sample).every(([key, value]) => key === 'date' ? ['2026-10-10', '2026-10-11'].includes(request.date) : request[key as keyof Request] === value));
 if (scenario < 0) throw new Error('Для этих параметров нет демонстрационной фикстуры. Выберите готовый пример; доступны даты 10 и 11 октября.');
 const count = scenario === 0 ? 3 : scenario === 1 ? 1 : 0;
 const codes: Reason[] = ['busy', 'format', 'budget', 'language', 'duration'];
 const names = request.date === '2026-10-11' ? ['Демо · ведущий Г', 'Демо · ведущий Б', 'Демо · ведущий Д'] : ['Демо · ведущий А', 'Демо · ведущий Б', 'Демо · ведущий В'];
 return { status: scenario === 3 ? 'category_missing' : count ? 'matches_found' : 'no_matches', message: scenario === 3 ? 'В демонстрационном сценарии нет флористов в этой локации. Измените город или категорию.' : scenario === 2 ? 'В демонстрационном сценарии все кандидаты исключены по бюджету. Попробуйте увеличить бюджет.' : scenario === 1 ? 'В демонстрационном сценарии подходит только один флорист: других кандидатов в категории нет.' : 'Показаны три из четырёх подходящих в демонстрационном сценарии. Порядок задан фикстурой.', total_in_category: scenario === 3 ? 0 : scenario === 1 ? 1 : 4, eligible_count: scenario === 0 ? 4 : count, returned_count: count, rejections: codes.map(code => ({ code, count: scenario === 2 && code === 'budget' ? 4 : 0 })), cards: Array.from({ length: count }, (_, i) => ({ id: `DEMO-${scenario}-${i}`, name: scenario === 1 ? 'Демо · флорист' : names[i], category: request.category, city: request.city, price_from_kzt: scenario === 1 ? 200000 : 250000 + i * 50000, languages: ['русский'], max_hours: scenario === 1 ? null : 5, explanation: `Учебный пример для формата «${request.event_format}»: ${scenario === 1 ? 'оформление цветочных композиций' : ['проведение интерактивных программ', 'работа с камерной аудиторией', 'сценарий с командными играми'][i]}. На ${request.date} не отмечен занятым в демонстрационном календаре.`, explanation_mode: 'local', evidence: [{ field: 'Источник', value: 'Вымышленная UI-фикстура, не профиль исходного каталога.' }, { field: 'Дата', value: request.date }, { field: 'Описание', value: scenario === 1 ? 'Цветочные композиции' : ['Интерактивная программа', 'Камерные мероприятия', 'Командные игры'][i] }], flags: { synthetic: true, city_imputed: i === 1, price_imputed: i === 2 } })) };
}
